### ISSUE TITLE
한 IP에서 1분 동안 10번 이상 요청 시 차단하는 AWS WAF를 구성

### ISSUE THREAD

**Issue by qj0r9j0vc2** [cloud-skills/study#1]
한 IP에서 1분 동안 10번 이상 요청 시 차단하는 AWS WAF를 구성을 위해서 Rate-based rule을 사용하려 하였으나, Rate-based rule은 5분 단위로만 요청 수를 계산하여 액션을 취하므로 위 예시를 충족시킬 수 없다고 생각됩니다. 

<br>
혹시, 다른 유형의 규칙을 사용하여 이를 해결할 수 있는 방법이 있을까요?

<br>
<br>
<br>
<br>

>  AWS WAF30초마다 요청 속도를 확인하고 매번 이전 5분 동안의 요청 수를 계산합니다.

https://docs.aws.amazon.com/ko_kr/waf/latest/developerguide/waf-rule-statement-type-rate-based-request-limiting.html

<br>
<br>

>  Q: [How to create customize AWS WAF Rate-based rule for 1min time window?](https://stackoverflow.com/questions/76040698/how-to-create-customize-aws-waf-rate-based-rule-for-1min-time-window)
> A: Unfortunately, not possible to do it that way with WAF.

https://stackoverflow.com/questions/76040698/how-to-create-customize-aws-waf-rate-based-rule-for-1min-time-window

**Comment by jukarch** [comment]
최소 단위를 파악하고 응용해서 5분에 50번으로 설정하라는 의도였는데 읽어보니 오해의 소지가 있겠네요. 5분에 50번으로 설정해서 풀어 보시면 됩니다.
