### ISSUE TITLE
Lambda Provisioned Concurrency 질문 드립니다.

### ISSUE THREAD

**Issue by yyeongjin** [cloud-skills/study#3]
람다 함수내에서 import time을 선언한 후, time.sleep(10)을 주어 람다함수를 배포하였습니다. 테스트를 진행하기 위해 Provisioned Concurrency를 1로 설정하고 동시에 20번 연속 Lambda 함수를 호출 하였습니다. 하지만 10초뒤에 "Hello from Lambda"가 응답되었습니다. Lambda 함수가 10초동안 실행되는데, 그 사이에 요청을 전송하는 행위는 동시에 호출한거나 다름 없는지 궁금합니다.

사용한 람다 코드는 다음과 같습니다.
import json
import time
def lambda_handler(event, context):
    time.sleep(10)
    return {
        'statusCode': 200,
        'body': json.dumps('Hello from Lambda!')
    }

**Comment by Jennas-Lee** [comment]
Lambda의 Provisioned Concurrency는 **함수 실행 자체의 동시성**이 아닌, **함수 실행 전 미리 프로비저닝**을 하는 기능입니다.

해당 AWS 공식 블로그가 아마 큰 도움이 될 것 같습니다.

https://aws.amazon.com/ko/blogs/korea/new-provisioned-concurrency-for-lambda-functions/

> Provisioned Concurrency가 비활성화된 함수의 경우 새 실행 환경을 생성해야 하고 함수 코드의 초기화가 늦어지므로 지연 시간이 추가됩니다.

Provisioned Concurrency를 1로 설정한다는 것은, 쉽게 비유하면 람다 컨테이너 1개를 미리 프로비저닝 함으로써 Cold Start로 인한 대기 및 지연시간을 줄이는 것이 그 목적이라고 볼 수 있습니다. 만약 람다 컨테이너 1개만으로 감당되지 않는 함수 호출의 경우에는 새로운 람다 컨테이너가 Cold Start함으로써 지연이 발생할 수 있겠습니다. (Throttling)

컴퓨팅 리소스를 미리 생성해놓는 개념이기 때문에 AWS는 해당 기능에 대해서 요금을 따로 받고 있습니다.

<img width="825" alt="Screenshot 2023-08-01 at 11 41 58 PM" src="https://github.com/cloud-skills/study/assets/55793046/0b3d9918-c255-4a31-af75-ae0d8f31681e">

---

질문자님께서 원하시는 기능은 아마 Reserved Concurrency 같습니다. 이 문서가 도움이 될 것 같습니다.

https://docs.aws.amazon.com/lambda/latest/dg/lambda-concurrency.html#reserved-and-provisioned

여기에 나온 그래프를 보시면, t3와 t4 사이에 들어오는 function_orange에 대한 호출은 빨간색으로 표시되어 있습니다. 함수 호출이 Reserved Concurrency를 초과하는 양에 대해선 Throttling이 걸리면서 함수 호출 몇개는 드랍될 것이라고 설명하고 있습니다.

---

추가로 몇마디 덧붙이자면, Provisioned Concurrency에 Auto Scaling를 적용하는 사례도 있습니다.

https://docs.aws.amazon.com/lambda/latest/dg/provisioned-concurrency.html#managing-provisioned-concurency
