### ISSUE TITLE
EKS MSA app Logging

### ISSUE THREAD

**Issue by ondacloud** [cloud-skills/study#4]
> 50개의 MSA app들이 300대의 EC2에서 돌고 있는 서비스가 있고, 각 app의 로깅 포맷이 현재 모두 다른 상황이다. EC2 환경에서 EKS 환경으로 마이그레이션 하고자 했을 때 로깅 아키텍처에 대해 설계해 보고 왜 그렇게 디자인하였는지 정리해 보세요.

라는 문제에서 50개의 MSA app들이 300대의 EC2에서 돌고 있는 서비스가 있고라는 말이 aws에서 50개의 MSA app을 사용하고 있으며 해등 app들을 EC2 300대를 통하여 서비스를 제공하고 있다는건지 궁금합니다.

**Comment by jukarch** [comment]
50개의 MSA 앱이 있는 서비스를 AWS에서 운영하고 있다는 얘기입니다. 그리고 앱 들이 모두 EC2에서 돌고 있고 EC2 개수가 300개 라는 뜻 입니다.

**Comment by jukarch** [comment]
50개가 아마존의 Route53, VPC 처럼 아마존 서비스를 뜻하는것이 아니라 내 서비스의 MSA 갯수를 의미하는 겁니다. MSA는 마이크로서비스 아키텍처를 뜻합니다.
