### ISSUE TITLE
Endpoint

### ISSUE THREAD

**Issue by jukarch** [cloud-skills/study#5]
북서수원고 홍길동 입니다.

http://aaa.example.io

**Comment by yyeongjin** [comment]
공주마이스터고 조영진 입니다.

http://k8s-default-zigiingr-f799bb9830-1489696099.ap-northeast-2.elb.amazonaws.com

**Comment by euichan2322** [comment]
금파공업고등학교 정의찬입니다.
http://app-alb-150561681.ap-northeast-2.elb.amazonaws.com/

**Comment by ArcoKim** [comment]
세명컴퓨터고등학교 김정태입니다.
http://skills-alb-1811079474.ap-northeast-2.elb.amazonaws.com/

**Comment by rlawoals2590** [comment]
세명컴퓨터고등학교 김재민입니다.
http://test-project-alb-171330205.ap-northeast-2.elb.amazonaws.com/
