### ISSUE TITLE
cloud-skills github

### ISSUE THREAD

**Issue by ondacloud** [cloud-skills/study#7]
클라우드 오프라인 강의 당시 클라우드 선수분들을 해당 cloud-skills github에 초대 해주신다고 하셨는데 해당 초대 코드는 언제 배부하실 계획이신가요?

**Comment by jukarch** [comment]
지도교사님들에게 온 아이디는 이미 전부 추가 하였습니다. 초대 필요하면 제게 메시지 주시거나 지도교사님 통해서 아이디 전달 해주시면 됩니다.
