### ISSUE TITLE
인증서를 통해 생성된 alb에 관한 질문입니다.

### ISSUE THREAD

**Issue by yyeongjin** [cloud-skills/study#8]
ALB에 인증서를 적용시키고 443를 80번포트로 리디렉션 작업을 대회에서도 똑같이 적용한다면 채점에 영향을 미칠까요?
http로 curl을 호출하면 301 Moved Permanently가 표시되고, 인증서는 로컬에서 발급받앗기에 https://로 curl을 호출하면 해당 오류가 발생하기 때문입니다. curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

**Comment by jukarch** [comment]
대회 채점 같은 경우는 문제 시나리오에 따라 다르기 때문에 절대적인 정답이 될 수 있는 케이스는 없습니다.

그 외 실제 사용 시나리오를 살펴 보자면, 보통 80 포트로 접근 하는 케이스를 막고 443 https 사용을 유도하기 위해 해당 작업을 진행합니다. 브라우저라면 응답 내용에 있는 location 주소로 재접속을 시도 하겠지만, curl은 한번 호출 후 응답을 받으면 끝나기 때문에 301 응답코드를 받고 호출은 정상 종료됩니다. 
301은 받은 후 끝나는게 정상이라 정확히 어떤 문제를 얘기 하는지는 모르겠으나, 아마 301 redirect 문제가 아니라 self-signed 형태의 인증서를 사용한 케이스에서 https 호출을 했을때 에러가 발생하는 상황을 얘기하는게 아닌가 싶습니다. 이 경우는 서버 인증서의 issuer를 증명할 수 있는 root 혹은 intermediate 인증서가 없기 때문에 서버의 신원을 밝힐 수 없다는 내용의 에러 입니다. 이때는 curl 호출시 별도의 CA 인증서를 지정해주거나 curl을 호출하는 PC 인증서 폴더에 서버 인증서의 issuer에 해당 하는 인증서를 넣어주면 에러는 보통 없어지게 됩니다.

만약 답변이 안되었다면 정확히 어떤 에러 케이스인지 확인해서 질문해주세요.
